CREATE SEQUENCE COLLECTION_DAY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DISTRICTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GARBAGE_COLLECTED_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GARBAGE_COLLECTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REGIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STATES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STREETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;